# Generated by Django 2.2 on 2019-04-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190405_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
    ]
